// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;


// import 'firebase_options.dart';

// // ...


// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDgA7Hwbp8P8ustw_U2zUIbvshQQ0h3teY',
//     appId: '1:1003721914662:web:cf0d722a1b7916ab0169e7',
//     messagingSenderId: '1003721914662',
//     projectId: 'flutter-first-8da0a',
//     authDomain: 'flutter-first-8da0a.firebaseapp.com',
//     storageBucket: 'flutter-first-8da0a.appspot.com',
//     measurementId: 'G-N0H6DY4011',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBhqlQtyo5XOLSlM9v2XTd4O_eKStL1B3k',
//     appId: '1:1003721914662:android:c49d643ba346506b0169e7',
//     messagingSenderId: '1003721914662',
//     projectId: 'flutter-first-8da0a',
//     storageBucket: 'flutter-first-8da0a.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDSva6s5gnqF3FOigFhzIQ2y9kXM4DHbM0',
//     appId: '1:1003721914662:ios:2210b07e7087de2d0169e7',
//     messagingSenderId: '1003721914662',
//     projectId: 'flutter-first-8da0a',
//     storageBucket: 'flutter-first-8da0a.appspot.com',
//     iosBundleId: 'com.example.app1',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDSva6s5gnqF3FOigFhzIQ2y9kXM4DHbM0',
//     appId: '1:1003721914662:ios:1d88951f7388a4d60169e7',
//     messagingSenderId: '1003721914662',
//     projectId: 'flutter-first-8da0a',
//     storageBucket: 'flutter-first-8da0a.appspot.com',
//     iosBundleId: 'com.example.app1.RunnerTests',
//   );
  
// //   await Firebase.initializeApp(
// //     options: DefaultFirebaseOptions.currentPlatform,
// // );
// }
